### PR TITLE
use goroutines to download images (4x faster)

### PR DESCRIPTION
**Pull request by ghost**
use [goroutines](https://gobyexample.com/goroutines) to speed up download times for big galleries

Downloading a 10 image gallery:
| goroutine | no goroutine |
| :------------: | :-----------: |
| 422.3982ms | 6.4326704s | 
| 306.2332ms | 1.4970517s |
| 265.9872ms | 1.6601041s |
| 517.3667ms | 1.62706s     |
| 321.5757ms | 1.6395222s |

doesn't make much of a difference for single image downloads, but for large galleries, the difference is very noticable.

### CODE REVIEW

**Comment by cmd777** [comment]
> i tried out this PR and i noticed you didn't add any waitgroup in [downloader_nos](https://github.com/noornee/reddit-dl/blob/3a7f3d3a8035eda6f14d3afcdc935cc1a380598d/service/downloader.go#L79)
> i tried adding a wait group and ran the script but there wasnt any notable difference and then it dawned on me that you added the waitgroup to the [downloader](https://github.com/noornee/reddit-dl/blob/3a7f3d3a8035eda6f14d3afcdc935cc1a380598d/service/downloader.go#L50) function because it's downloading 2 different files(audio & video) hence concurrency!...TIL :)

Spot on. It also concurrently downloads all images from the media_url in the [main](https://github.com/noornee/reddit-dl/pull/6/commits/f0e699bd92f9fec56fa85914bd321438e28ba367#diff-38035a4d07316d9007b9d9ad9016d46f0f25321f17a3fef07c2b4159d8360528) program, (prob the biggest speedup tho, but again, not much of a difference for 1-2 images)

Also, perhaps instead of requiring go to install the tool, how about a workflow that builds the main package and then uploads the files?

**Comment by noornee** [comment]
> Spot on. It also concurrently downloads all images from the media_url in the [main](https://github.com/noornee/reddit-dl/pull/6/commits/f0e699bd92f9fec56fa85914bd321438e28ba367#diff-38035a4d07316d9007b9d9ad9016d46f0f25321f17a3fef07c2b4159d8360528) program, (prob the biggest speedup tho, but again, not much of a difference for 1-2 images)
> 

yeah, i noticed that!
> Also, perhaps instead of requiring go to install the tool, how about a workflow that builds the main package and then uploads the files?

hmm, i haven't done this before
I'm gonna research how it's done and see how that works andd how are users going to install it ?

**Comment by cmd777** [comment]
> hmm, i haven't done this before
> I'm gonna research how it's done and see how that works andd how are users going to install it ?

They can install it with go install, or if you do make a workflow for it, they will be able to just go to the releases page and download it there, though I'm not sure if it interferes with go get / go install (I don't think it will, though.)

Feel free to use [these](https://github.com/cmd777/lex/tree/main/.github/workflows) workflows as a template, and edit it to your liking, or if you need help, then I'll try to help ya with those workflows, but no promises, i'm not big into workflows.

**Comment by noornee** [comment]
> or if you do make a workflow for it, they will be able to just go to the releases page and download it there

i see, so they wouldn't need to have go installed to be able to run it ? neat!

> Feel free to use [these](https://github.com/cmd777/lex/tree/main/.github/workflows) workflows as a template, and edit it to your liking (probably should change the cron job, and remove minify & zipping)

for some reason, i feel you're my guardian angel!!


> if you need help, then I'll try to help ya with those workflows, but no promises, i'm not big into workflows.

Thankss, I'm going to try doing this myself and if i have any issues with it, i shall come for ya!

**Comment by cmd777** [comment]
> i see, so they wouldn't need to have go installed to be able to run it ? neat!

Yeah, exactly. 

> for some reason, i feel you're my guardian angel!!

:)

> Thankss, I'm going to try doing this myself and if i have any issues with it, i shall come for ya!

Alright, best of luck with it

**Pull request merged**
