### PR TITLE
Fix some bugs, minor cleanup & fix issue #1

### LINKED ISSUE #1: Can't get lesbians. Help!
```
$ reddit-dl -url https://www.reddit.com/r/Lesbian_gifs/comments/zvx95q/our_favourite_position_is_69
[INFO]: Parsing The URL
[INFO]: Getting the JSON body
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/noornee/reddit-dl/utility.ParseJSONBody({0xc000258500, 0x23bd, 0x2500})
        /git/reddit-dl/utility/utility.go:111 +0x7f7
main.main()
        /git/reddit-dl/main.go:42 +0x219
```

### PR DESCRIPTION
**Pull request by cmd777**
Fixes #1 

utility.go should be completely reworked, it's really inneficient, and hard to read & use.
or if not reworked, just use a struct, like so.

also, should use HLS instead of relying on DASH (ffmpeg supports HLS -> mp4) (https://stackoverflow.com/questions/33108105/converting-an-hls-m3u8-to-mp4)
```go
type Data struct {
    Children []struct {
        Data struct {
            URLOverridenbyDest string `json:"url_overridden_by_dest"`
        }  `json:"data"`
    } `json:"children"`
} `json:"data"`
```

### CODE REVIEW

**Comment by noornee** [comment]
Hii @cmd777 Thanks a lot for your pointers and the contributions you've made. i'm excited!

yes, utility.go does seem hard to read. i didn't want to use struct becasue i thought it would be longer?
like making structs tags for all the fields. but i'm going to rework it and use structs. if possible, you could make the changes yourself and i would be happy to merge it!

andd i'm going to switch to using HLS, i never really bothered to research further on it because it seemed like a text file with contents i didn't understand until now.
Thanks for the stackoverflow link!

**Comment by noornee** [comment]
> also, should use HLS instead of relying on DASH (ffmpeg supports HLS -> mp4) (https://stackoverflow.com/questions/33108105/converting-an-hls-m3u8-to-mp4)
 
 Hi @cmd777 , so i tried download some videos from hls_url but the best quality of the videos turned out blurry

**Comment by cmd777** [comment]
> i didn't want to use struct becasue i thought it would be longer?
> like making structs tags for all the fields.

Sometimes, structs can be larger, like this example
```go
type Reddit struct {
	Data struct {
		Children []struct {
			Data struct {
				ID      string `json:"name"`
				Preview struct {
					VideoPreview struct { // struct names do not need to match
						HLS string `json:"hls_url"` // nor do struct element names, but the json still has to match.
					} `json:"reddit_video_preview"` // `json:"..."` names must match.
				} `json:"preview"`
			} `json:"data"`
		} `json:"children"`
	} `json:"data"`
}
```
Not all struct tags are required for it to work, and their name can be changed, except for the `json:""` part.

> so i tried download some videos from hls_url but the best quality of the videos turned out blurry

I just tried it out. On some videos, the width, height, and the bitrate seems to change. I did change the options a bit, to simply use `ffmpeg -i ...m3u8 -c copy video.mp4`, but it shouldn't be blurry.
As to why the options were changed, check out [this](https://gist.github.com/tzmartin/fb1f4a8e95ef5fb79596bd4719671b5d?permalink_comment_id=3331567#gistcomment-3331567) comment.
for example,. from width 608 -> 404
from height 1080 -> 720
and from bitrate 4737863 -> 2367167
This only seems to happen to videos from gyfcat or imgur

**Comment by noornee** [comment]
> Not all struct tags are required for it to work, and their name can be changed, except for the `json:""` part.

ohhh, omg, i thought I'd have to write tags for all the fields. i understand what i have to do now, Thanks!

> `ffmpeg -i ...m3u8 -c copy video.mp4`, but it shouldn't be blurry.

yeah, i did this too

> This only seems to happen to videos from gyfcat or imgur

yes it seems so, i haven't tried it with videos on gfycat but i tried it with a gif/video with no sound and it got reduced

**Comment by noornee** [comment]
> ```go
> type Reddit struct {
> 	Data struct {
> 		Children []struct {
> 			Data struct {
> 				ID      string `json:"name"`
> 				Preview struct {
> 					VideoPreview struct { // struct names do not need to match
> 						HLS string `json:"hls_url"` // nor do struct element names, but the json still has to match.
> 					} `json:"reddit_video_preview"` // `json:"..."` names must match.
> 				} `json:"preview"`
> 			} `json:"data"`
> 		} `json:"children"`
> 	} `json:"data"`
> }
> ```

Thanks for this!

**Comment by cmd777** [comment]
> > ```go
> > type Reddit struct {
> > 	Data struct {
> > 		Children []struct {
> > 			Data struct {
> > 				ID      string `json:"name"`
> > 				Preview struct {
> > 					VideoPreview struct { // struct names do not need to match
> > 						HLS string `json:"hls_url"` // nor do struct element names, but the json still has to match.
> > 					} `json:"reddit_video_preview"` // `json:"..."` names must match.
> > 				} `json:"preview"`
> > 			} `json:"data"`
> > 		} `json:"children"`
> > 	} `json:"data"`
> > }
> > ```
> 
> Thanks for this!

You're welcome. Just a heads up, I used the results from `https://reddit.com/r/gifs.json` to make that struct, and it will look different than a comments' json.

> ohhh, omg, i thought I'd have to write tags for all the fields. i understand what i have to do now, Thanks!

Have a read at the golang docs about json, It's very useful https://pkg.go.dev/encoding/json

There is also a tool to convert json to go structs, but it's very outdated (eg, doesn't recognize struct arrays sometimes, and still uses interface{}) https://mholt.github.io/json-to-go/

You can also try experimenting with go json structs with either
https://xkcd.com/info.0.json (this is super simple, as it only consists of a few strings, ints.)
or https://json.org/example.html (if you do use this, which is a bit more complicated than xkcd, I highly recommend you use a JSON Formatter like this https://jsonformatter.org/json-pretty-print)

**Comment by noornee** [comment]
> You're welcome. Just a heads up, I used the results from `https://reddit.com/r/gifs.json` to make that struct, and it will look different than a comments' json.

(>w<)

ohh, i thought it looked weird because reddit-dl doesn't take data from the video_preview tag


> Have a read at the golang docs about json, It's very useful https://pkg.go.dev/encoding/json

okayy, I'll take my time to understand it properly 


> There is also a tool to convert json to go structs, but it's very outdated (eg, doesn't recognize struct arrays sometimes, and still uses interface{}) https://mholt.github.io/json-to-go/

Thanks, I'll try it out 

i also found some other [site](https://transform.tools/json-to-go) we could use to covert json to structs but i haven't tried it out yet

**Comment by noornee** [comment]
this is what i have right now 

```go
type Reddit []struct {
	Kind string `json:"kind"`
	Data struct {
		Children []struct {
			Data struct {
				//MediaMetadata mediaMetadata `json:"media_metadata"`
				SecureMedia struct {
					Oembed      oembed `json:"oembed"`
					RedditVideo struct {
						FallbackURL string `json:"fallback_url"`
						HlsURL      string `json:"hls_url"`
					} `json:"reddit_video"`
				} `json:"secure_media"`
				CrosspostParentList crosspostParentList `json:"crosspost_parent_list"`
				IsRedditMediaDomain bool                `json:"is_reddit_media_domain"`
				URLOverriddenByDest string              `json:"url_overridden_by_dest"`
			} `json:"data"`
		} `json:"children"`
	} `json:"data"`
}

// for files shared from another domain i.e gfycat.com 
type oembed struct {
	ProviderURL  string `json:"provider_url"`
	ThumbnailURL string `json:"thumbnail_url"`
}

// for cross posts
type crosspostParentList []struct {
	SecureMedia struct {
		RedditVideo struct {
			FallbackURL string `json:"fallback_url"`
			HlsURL      string `json:"hls_url"`
		} `json:"reddit_video"`
	} `json:"secure_media"`
	URLOverriddenByDest string `json:"url_overridden_by_dest"`
}

// would make chages to this later
//type mediaMetadata struct {
//Ymzg2Pr2Si0A1 struct {
//S struct {
//U string `json:"u"`
//} `json:"s"`
//} `json:"ymzg2pr2si0a1"`
//}
```

**Comment by cmd777** [comment]
> this is what i have right now

Why did you use pointers? They're mostly used to share data. Here, they are really not needed.
Also, you should probably export those structs (just capitalize the first letter, like: SecureMedia or CrosspostParentList)

as for Galleries (MediaMetaData) use this.
```go
Gallery map[string]struct {
	P []struct {
		U string `json:"u"`
	} `json:"p"`
} `json:"media_metadata"`
```

and use a range loop over it

```go
var r2 Reddit

for _, k := range r2[0].Data.Children[0].Data.Gallery {
	fmt.Println(k.P[len(k.P)-1].U)
}
```

**Comment by noornee** [comment]
> Why did you use pointers? They're mostly used to share data. Here, they are really not needed.

check here -> https://stackoverflow.com/questions/18088294/how-to-not-marshal-an-empty-struct-into-json-with-go
i made some [conditional](https://github.com/noornee/reddit-dl/blob/85a2e0140040221c94f5f75873f06d7ec77082fd/utility/utility.go#L43) statements to check if they're nil that's why i did that


> as for Galleries (MediaMetaData) use this.
> 
i cant use that because the struct tags are dynamic.
i figured out a [way](https://github.com/noornee/reddit-dl/blob/85a2e0140040221c94f5f75873f06d7ec77082fd/model/models.go#L9) to do this but i'm not so sure if it's a good practice 

check `media_metadata`  here -> https://www.reddit.com/r/neovim/comments/ygx031/html_treesitter_syntax_higlighting_gone.json

**Comment by cmd777** [comment]
> check here -> https://stackoverflow.com/questions/18088294/how-to-not-marshal-an-empty-struct-into-json-with-go
> i made some [conditional](https://github.com/noornee/reddit-dl/blob/85a2e0140040221c94f5f75873f06d7ec77082fd/utility/utility.go#L43) statements to check if they're nil that's why i did that

Ah, yeah. sorry. I was a bit tired

> i cant use that because the struct tags are dynamic.
> i figured out a [way](https://github.com/noornee/reddit-dl/blob/85a2e0140040221c94f5f75873f06d7ec77082fd/model/models.go#L9) to do this but i'm not so sure if it's a good practice

json.RawMessage is exactly what the name is, json raw message, it still includes the dynamic tags.
however, if you use a `map[string]struct`
```go
MMD map[string]struct {
	P []struct {
		U string `json:"u"`
	} `json:"p"`
} `json:"media_metadata"`

// ...

for _, k := range struct1[0].Data.Children[0].Data.MMD {
	fmt.Println(k.P[len(k.P)-1].U)
}

```
and then use VSCode and hover over k, you will see that it's a struct now
```go
var k struct{P []struct{U string "json:\"u\""} "json:\"p\""}
```
and that blank identifier (_) would be the name of that dynamic tag, as if you reverse that for range
```go
for k := range struct1[0].Data.Children[0].Data.MMD {
	fmt.Println(k)
}
```
it will only print those struct tags, and not gallery image urls

**Comment by noornee** [comment]
> Ah, yeah. sorry. I was a bit tired

oh, there's no problemo hehe. take care...

> however, if you use a `map[string]struct`

woww, i just tried it and it works!
good stuff you did right here :)

could you make a pr with the new changes?

gimmie a sec

**Comment by cmd777** [comment]
> could you make a pr if you're less preoccupied with the new changes?

Oops, was away. Sorry.

> in the metadata, I'm only getting the images from the `s["u"]` tag not `p`, i chose this because the images are of the highest resolution

Oh yes, using the S struct is way better, since that's the source image, the P array contains resized images. I just copy pasted that from my code and rewrote it to use the last item in the list, which I thought would be the same as the source one, but turns out, it's not. It's similar in quality, but the source has a bit better quality.

> [edit]
> hey, i've [modified](https://github.com/noornee/reddit-dl/commit/880a6d3d6252f2697733875b195e6f954bdd196d) it already. wouldnt have figured it out this soon without you. Thanks!

Glad you figured it out, and you're very welcome!

**Comment by noornee** [comment]
> Oops, was away. Sorry.

there's no problemo :)

>  I just copy pasted that from my code and rewrote it to use the last item in the list, which I thought would be the same as the source one, but turns out, it's not. 

yeah, i realized.

> It's similar in quality, but the source has a bit better quality.
 
exactly!

> Glad you figured it out, and you're very welcome!

hehe, xD

**Pull request merged**
